name: Gradle Package

on:
  push:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Run chmod to make gralew executable
        run: chmod +x ./gradlew

      - name: Create appliction-test.properties
        run: | 
          touch ./src/main/resources/application-test.properties
          echo "${{ secrets.APPLICATION_TEST }}" > ./src/main/resources/application-test.properties
          cat ./src/main/resources/application-test.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql database: 'jamrello_test'
          mysql password: 'test'
          mysql user: 'root'

      - name: Build with Gradle
        # uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        run: |
          ./gradlew build -x test
        # with:
          # arguments: build
      - name: Test with Gradle
        run: | 
          ./gradlew test -Dspring.config.location=classpath:application-test.properties

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #테스트 테스트..ㅠㅠ
